### ISSUE TITLE
db2 webhelp and db2 cli commands not working despite plugins list saying its installed  

### ISSUE THREAD

**Issue by mpanch59** [zowe/zowe-cli-db2-plugin#59]
Hi

Despite the db2 cli being installed , the webhelp is not showing and commands are not working correctly when trying to create a profile on Windows 

C:\Users\TEST\.zowe\plugins\installed\node_modules\@zowe\db2-for-zowe-cli>zowe plugins list

Installed plugins:

 -- pluginName: @zowe/secure-credential-store-for-zowe-cli
 -- package: @zowe/secure-credential-store-for-zowe-cli@zowe-v1-lts
 -- version: 4.1.0
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/cics-for-zowe-cli
 -- package: @zowe/cics-for-zowe-cli@zowe-v1-lts
 -- version: 4.0.2
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/db2-for-zowe-cli
 -- package: @zowe/db2-for-zowe-cli
 -- version: 4.0.6
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/ims-for-zowe-cli
 -- package: @zowe/ims-for-zowe-cli@zowe-v1-lts
 -- version: 2.0.1
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/mq-for-zowe-cli
 -- package: @zowe/mq-for-zowe-cli@zowe-v1-lts
 -- version: 2.0.1
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/zos-ftp-for-zowe-cli
 -- package: @zowe/zos-ftp-for-zowe-cli@zowe-v1-lts
 -- version: 1.2.0
 -- registry: https://registry.npmjs.org/

no db2 help available 

![image](https://user-images.githubusercontent.com/47594439/97164145-9a2c2c80-1779-11eb-8feb-750a1969eef8.png)

**Comment by mpanch59** [comment]
C:\Users\TEST>zowe plugins install @zowe/db2-for-zowe-cli
Plug-ins within the Imperative CLI Framework can legitimately gain
control of the zowe CLI application during the execution of every command.
Install 3rd party plug-ins at your own risk.

Imperative's plugin installation program handles @zowe peer dependencies.
You can safely ignore NPM warnings about missing @zowe peer dependencies.

Registry = https://registry.npmjs.org/

_______________________________________________________________
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN @zowe/db2-for-zowe-cli@4.0.6 requires a peer of @zowe/imperative@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/db2-for-zowe-cli@4.0.6 requires a peer of @zowe/cli@^6.0.0 but none is installed. You must install peer dependencies yourself.

Installed plugin name = '@zowe/db2-for-zowe-cli'

_____ Validation results for plugin '@zowe/db2-for-zowe-cli' _____
This plugin was successfully validated. Enjoy the plugin.

**Comment by MikeBauerCA** [comment]
The issue was resolved be deleting the `.zowe/web-help` folder under the home directory and issuing the `zowe --hw` command to regen the web help.

Ideally, the web help should be regenerated the next time the `--hw` flag is used after installing the plug-in without the need to delete the `web-help` folder.

**Comment by FALLAI-Denis** [comment]
Problem still present...
"text mode help" is OK.
Only the Db2 plugin presents this problem.

**Comment by zFernand0** [comment]
It seems that newer version of the CLI may have fixed this issue.
I was able to run `zowe --hw` after installing the latest version of the db2 plug-in.

Closing. Feel free to re-open if the issue still persist.
